// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kumbxdfrnsyivifmhvfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1bWJ4ZGZybnN5aXZpZm1odmZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjM2NDIsImV4cCI6MjA2NDc5OTY0Mn0.kRGq_VUBp0bPx_L_2Fv_AjiMQeM7l_JvFZ12ekRnSmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);